# Generated by Django 4.2.1 on 2023-05-30 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reply',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_post',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='post',
            name='saves_posts',
            field=models.ManyToManyField(blank=True, related_name='blog_posts_save', to=settings.AUTH_USER_MODEL, verbose_name='Сохранённые посты пользователя'),
        ),
    ]
