# Generated by Django 4.2.1 on 2023-05-31 10:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_likes_remove_post_reply_post_likes_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='не более 5000 символов', max_length=5000, null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, help_text='не более 200 символов', max_length=200, verbose_name='Название'),
        ),
    ]
